import Banner from "../components/banner/Banner";

export default function Home() {
    return (
        <div>
            <Banner imageURL="https://wallpaperaccess.com/full/2122580.png" subtitle="Taking conversations to the moon! 🚀" title="S K Y L I X" />

            {/* <h1 style={{
                textAlign: "center",
            }}>S K Y L I X</h1>

            <p style={{
                textAlign: "center",
            }}>
                Taking conversations to the moon! 🚀
            </p> */}

            <h3>Skylix isn{ "'" }t ready yet!</h3>
            <p>Skylix is still in dev, check out our github for more info like our discord server, etc...</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui impedit maxime esse dolorem porro natus cupiditate pariatur officiis culpa, placeat, corporis rerum sunt? Pariatur exercitationem ad nostrum est? Sit optio maxime similique. Consequatur, animi facere. Rem deleniti qui recusandae excepturi. Sapiente harum, dolore corrupti error animi sint eligendi asperiores facere quae, quisquam veniam, aliquam sunt maxime accusamus placeat! Harum suscipit et, architecto illum blanditiis quo natus distinctio voluptatibus totam, consequatur, officiis aut. Illo ducimus quibusdam aliquid esse incidunt, nemo consequuntur doloribus explicabo. Nostrum ipsum inventore officiis quaerat doloribus magnam adipisci, aliquam accusantium placeat voluptatum porro dolores eum libero perferendis rem asperiores iusto error voluptas. Atque officiis nesciunt voluptatibus, vel quidem laudantium beatae minima nihil dolorum, obcaecati nulla dignissimos numquam quo? Modi inventore non error itaque molestias accusamus repudiandae soluta dolorum pariatur consequuntur, commodi corrupti tempore porro numquam nostrum explicabo doloremque reiciendis nulla sit temporibus in! Accusantium ratione praesentium omnis reprehenderit ab quam similique sapiente tempore eius quibusdam non numquam fuga reiciendis, officia id. Saepe officiis ad nemo ullam porro, labore, voluptatem quas expedita veritatis, id eaque. Reiciendis ratione voluptas sapiente fugit aut consequuntur magnam laudantium fuga impedit vel, necessitatibus modi labore qui iure. Aliquam saepe veritatis recusandae doloribus odio ab deleniti, expedita quas voluptatum quo unde porro! Adipisci cupiditate labore libero perspiciatis facere quo aspernatur tenetur sed, dignissimos numquam esse officia enim ipsum iusto laboriosam! Cumque, minus nemo. Consequuntur, incidunt! Omnis tempora, iure voluptatem non dolorum at amet excepturi quaerat eos asperiores totam ipsa iste quibusdam debitis. Ratione necessitatibus ad esse vitae, dolore distinctio quo odio ipsa ipsum beatae cupiditate explicabo nam aliquam, dolor iusto numquam dolorem id officiis quidem et nobis? Ratione, architecto? Eaque saepe rem reiciendis quia sed, nostrum veritatis perferendis cupiditate quasi sunt cumque distinctio molestiae enim molestias consequatur architecto laborum sequi adipisci dolor incidunt delectus ab.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui impedit maxime esse dolorem porro natus cupiditate pariatur officiis culpa, placeat, corporis rerum sunt? Pariatur exercitationem ad nostrum est? Sit optio maxime similique. Consequatur, animi facere. Rem deleniti qui recusandae excepturi. Sapiente harum, dolore corrupti error animi sint eligendi asperiores facere quae, quisquam veniam, aliquam sunt maxime accusamus placeat! Harum suscipit et, architecto illum blanditiis quo natus distinctio voluptatibus totam, consequatur, officiis aut. Illo ducimus quibusdam aliquid esse incidunt, nemo consequuntur doloribus explicabo. Nostrum ipsum inventore officiis quaerat doloribus magnam adipisci, aliquam accusantium placeat voluptatum porro dolores eum libero perferendis rem asperiores iusto error voluptas. Atque officiis nesciunt voluptatibus, vel quidem laudantium beatae minima nihil dolorum, obcaecati nulla dignissimos numquam quo? Modi inventore non error itaque molestias accusamus repudiandae soluta dolorum pariatur consequuntur, commodi corrupti tempore porro numquam nostrum explicabo doloremque reiciendis nulla sit temporibus in! Accusantium ratione praesentium omnis reprehenderit ab quam similique sapiente tempore eius quibusdam non numquam fuga reiciendis, officia id. Saepe officiis ad nemo ullam porro, labore, voluptatem quas expedita veritatis, id eaque. Reiciendis ratione voluptas sapiente fugit aut consequuntur magnam laudantium fuga impedit vel, necessitatibus modi labore qui iure. Aliquam saepe veritatis recusandae doloribus odio ab deleniti, expedita quas voluptatum quo unde porro! Adipisci cupiditate labore libero perspiciatis facere quo aspernatur tenetur sed, dignissimos numquam esse officia enim ipsum iusto laboriosam! Cumque, minus nemo. Consequuntur, incidunt! Omnis tempora, iure voluptatem non dolorum at amet excepturi quaerat eos asperiores totam ipsa iste quibusdam debitis. Ratione necessitatibus ad esse vitae, dolore distinctio quo odio ipsa ipsum beatae cupiditate explicabo nam aliquam, dolor iusto numquam dolorem id officiis quidem et nobis? Ratione, architecto? Eaque saepe rem reiciendis quia sed, nostrum veritatis perferendis cupiditate quasi sunt cumque distinctio molestiae enim molestias consequatur architecto laborum sequi adipisci dolor incidunt delectus ab.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui impedit maxime esse dolorem porro natus cupiditate pariatur officiis culpa, placeat, corporis rerum sunt? Pariatur exercitationem ad nostrum est? Sit optio maxime similique. Consequatur, animi facere. Rem deleniti qui recusandae excepturi. Sapiente harum, dolore corrupti error animi sint eligendi asperiores facere quae, quisquam veniam, aliquam sunt maxime accusamus placeat! Harum suscipit et, architecto illum blanditiis quo natus distinctio voluptatibus totam, consequatur, officiis aut. Illo ducimus quibusdam aliquid esse incidunt, nemo consequuntur doloribus explicabo. Nostrum ipsum inventore officiis quaerat doloribus magnam adipisci, aliquam accusantium placeat voluptatum porro dolores eum libero perferendis rem asperiores iusto error voluptas. Atque officiis nesciunt voluptatibus, vel quidem laudantium beatae minima nihil dolorum, obcaecati nulla dignissimos numquam quo? Modi inventore non error itaque molestias accusamus repudiandae soluta dolorum pariatur consequuntur, commodi corrupti tempore porro numquam nostrum explicabo doloremque reiciendis nulla sit temporibus in! Accusantium ratione praesentium omnis reprehenderit ab quam similique sapiente tempore eius quibusdam non numquam fuga reiciendis, officia id. Saepe officiis ad nemo ullam porro, labore, voluptatem quas expedita veritatis, id eaque. Reiciendis ratione voluptas sapiente fugit aut consequuntur magnam laudantium fuga impedit vel, necessitatibus modi labore qui iure. Aliquam saepe veritatis recusandae doloribus odio ab deleniti, expedita quas voluptatum quo unde porro! Adipisci cupiditate labore libero perspiciatis facere quo aspernatur tenetur sed, dignissimos numquam esse officia enim ipsum iusto laboriosam! Cumque, minus nemo. Consequuntur, incidunt! Omnis tempora, iure voluptatem non dolorum at amet excepturi quaerat eos asperiores totam ipsa iste quibusdam debitis. Ratione necessitatibus ad esse vitae, dolore distinctio quo odio ipsa ipsum beatae cupiditate explicabo nam aliquam, dolor iusto numquam dolorem id officiis quidem et nobis? Ratione, architecto? Eaque saepe rem reiciendis quia sed, nostrum veritatis perferendis cupiditate quasi sunt cumque distinctio molestiae enim molestias consequatur architecto laborum sequi adipisci dolor incidunt delectus ab.</p>
        </div>
    );
}
